# This workflow will build and deploy a Node.js app to an Azure Web App
# It is designed to work with your static HTML file and the Node.js Azure Function.

name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main # Change this to your deployment branch if needed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a supported Node.js version

      - name: Install dependencies
        run: npm install

      # Build your function app if needed (for more complex projects)
      # For your simple function, this step might not be required.

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .
            !venv/ # Exclude any Python virtual environment files

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chopitupchat2' # Replace with your App Service name
          slot-name: 'Production'
          # Use the publish profile or service principal for authentication
          # Replace with your actual credentials
          # Use a secret for publish-profile in GitHub
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.' # Deploys the root directory
