# .github/workflows/apollo_sightsound-func-apollo.yml
name: Deploy Sight & Sound Functions

on:
  push:
    branches: [ Apollo ]
    paths:
      - 'sight-sound-tour/api/**'
      - '.github/workflows/apollo_sightsound-func-apollo.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy ONLY the Functions subfolder (host.json at this path)
      - name: Deploy Functions
        uses: azure/functions-action@v1
        with:
          app-name: sightsound-func-apollo
          package: sight-sound-tour/api
          scm-do-build-during-deployment: true
